{"version":3,"sources":["components/AlertRenderer/ConferenceCallAlert/i18n/en-US.ts"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAGGA,kCAAqBC,a,EAAgB,6E,0CACrCD,kCAAqBE,oB,EAAuB,6E,0CAC5CF,kCAAqBG,yB,EAA4B,mF,0CACjDH,kCAAqBI,0B,EAA6B,oF,0CAClDJ,kCAAqBK,e,EAAkB,kE","sourcesContent":["import conferenceCallErrors from '@ringcentral-integration/commons/modules/ConferenceCall/conferenceCallErrors';\n\nexport default {\n  [conferenceCallErrors.bringInFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.makeConferenceFailed]: 'Failed to merge the calls due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.terminateConferenceFailed]: 'Failed to hangup the conference due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.removeFromConferenceFailed]: 'Failed to remove the participant due to unexpected errors. Please try again later.',\n  [conferenceCallErrors.callIsRecording]: 'Call recording in progress. Please stop recording and try again.',\n};\n"],"file":"en-US.js"}