{"version":3,"sources":["components/AlertRenderer/ConferenceCallAlert/i18n/zh-HK.ts"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAEGA,kCAAqBC,a,EAAgB,0B,0CACrCD,kCAAqBE,oB,EAAuB,0B,0CAC5CF,kCAAqBG,yB,EAA4B,4B,0CACjDH,kCAAqBI,0B,EAA6B,2B,0CAClDJ,kCAAqBK,e,EAAkB,uB,2BAG1C;AACA;AACA;AACA;AACA","sourcesContent":["import conferenceCallErrors from '@ringcentral-integration/commons/modules/ConferenceCall/conferenceCallErrors';\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"因為意外發生錯誤，合併通話失敗。請稍後再試一次。\",\n  [conferenceCallErrors.makeConferenceFailed]: \"因為意外發生錯誤，合併通話失敗。請稍後再試一次。\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"因為意外發生錯誤，掛斷電話會議失敗。請稍後再試一次。\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"因為意外發生錯誤，移除參與者失敗。請稍後再試一次。\",\n  [conferenceCallErrors.callIsRecording]: \"通話錄音進行中。請停止錄音並稍後再試一次。\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.callIsRecording]\"@#@ @source: @#@\"Call recording in progress. Please stop recording and try again.\"@#@\n"],"file":"zh-HK.js"}